Types of methods to be used:
1. Cross-Correlation Analysis
2. Granger Causality Test
3. VAR Model
4. Impulse Response Analysis
5. Lagged Regression Analysis 

In [1]:
import MetaTrader5 as mt5
from datetime import datetime
import pytz
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
import numpy as np
import warnings
warnings.filterwarnings("ignore")
mt5.initialize()
account=51127988
password="Aar2frM7"
server = 'ICMarkets-Demo'

In [328]:
def get_rates(pair1, tf, x):
    pair1 = pd.DataFrame(mt5.copy_rates_from_pos(pair1, tf, 0, x))
    pair1['time'] = pd.to_datetime(pair1['time'], unit = 's')
    pair1 = pair1.set_index(pair1['time'])
    pair1 = pair1.drop(columns = ['time','tick_volume', 'spread', 'real_volume'])
    return pair1
def corr_measure():
    if pearson_corr[0][1] > abs(0.5):
        print(f'Lag {i} shows a moderate correlation')
    else:
        print(f'No Correlation at {i}')

## Hypothesis 

The movements of the EURUSD and GBPUSD exchange rates can be used to predict the future direction of the USDJPY exchange rate. Specifically, if both EURUSD and GBPUSD experience an increase within a given time period (e.g., within one hour), there is a statistically significant probability that the USDJPY exchange rate will decrease in the subsequent time period.

## Method

Gather hourly data of EURUSD and GBPUD. Process the data so that the remaining data are EURUSD and GBPUSD candles that are correlated and have moved more than 10 pips.

Gather USDJPY hourly candles for each time period succeeding the new data points gathered.

Run a Pearson correlation analysis between the EURUSD-GBPUSD amended data and USDJPY data.



In [313]:
EU = get_rates('EURUSD.a', mt5.TIMEFRAME_H1, 10000)
GU = get_rates('GBPUSD.a', mt5.TIMEFRAME_H1, 10000)
EU_returns = pd.DataFrame(10000 * (EU['close'] - EU['open']))
EU_returns.rename(columns = {0:'EU'}, inplace = True)
GU_returns = pd.DataFrame(10000 * (GU['close'] - GU['open']))
GU_returns.rename(columns = {0:'GU'}, inplace = True)
# GU_returns.rename('GU', inplace = True)
EU_returns = EU_returns[abs(EU_returns) > 10]
GU_returns = GU_returns[abs(GU_returns) > 10]

EU_GU = pd.concat([EU_returns, GU_returns], axis = 1)
EU_GU = EU_GU.dropna()
EU_GU = EU_GU.rename(columns={0: 'EURUSD', 0: 'GBPUSD'})
EU_GU["Spread"] = EU_GU['EU'] - EU_GU['GU']
EU_GU

EU    GU  Spread
time                                   
2021-11-15 19:00:00 -35.4 -21.1   -14.3
2021-11-15 22:00:00 -25.5 -20.9    -4.6
2021-11-16 16:00:00 -18.0 -33.8    15.8
2021-11-16 21:00:00 -10.7 -10.2    -0.5
2021-11-17 05:00:00 -33.2 -17.0   -16.2
...                   ...   ...     ...
2023-06-20 12:00:00 -12.8 -17.0     4.2
2023-06-20 19:00:00  15.2  26.0   -10.8
2023-06-21 11:00:00  12.2 -16.0    28.2
2023-06-21 17:00:00  28.0  10.7    17.3
2023-06-21 19:00:00  20.2  21.1    -0.9

[2097 rows x 3 columns]

In [339]:
UJ = get_rates('USDJPY.a', mt5.TIMEFRAME_H1, 10000)
UJ_returns = pd.DataFrame(UJ['close'] - UJ['open'])
UJ_returns.rename(columns = {0:'UJ'}, inplace = True)

In [335]:
for i in range(1, 24):
    # Shift the index in df2 back by one hour
    UJ_returns.index = UJ_returns.index - pd.Timedelta(hours=i)

    # Keep only the rows in UJ_returns that match the index in df1
    UJ_returns = UJ_returns[UJ_returns.index.isin(EU_GU.index)]
    
    pearson_corr = np.corrcoef(EU_GU['EU'].tail(2090), UJ_returns['UJ'].tail(2090))
    corr_measure()
    pearson_corr = np.corrcoef(UJ_returns['UJ'].tail(2090), EU_GU['GU'].tail(2090))
    corr_measure()
    pearson_corr = np.corrcoef(EU_GU['EU'].tail(2090), UJ_returns['UJ'].tail(2090))
    corr_measure()

No Correlation at 1
No Correlation at 1
No Correlation at 1


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2090 and the array at index 1 has size 624

In [340]:
# Shift the index in df2 back by one hour
UJ_returns.index = UJ_returns.index - pd.Timedelta(hours=1)

# Keep only the rows in UJ_returns that match the index in df1
UJ_returns = UJ_returns[UJ_returns.index.isin(EU_GU.index)]
UJ_returns

UJ
time                      
2021-11-15 19:00:00 -0.008
2021-11-15 22:00:00 -0.029
2021-11-16 16:00:00 -0.036
2021-11-16 21:00:00  0.130
2021-11-17 05:00:00 -0.029
...                    ...
2023-06-20 12:00:00 -0.221
2023-06-20 19:00:00  0.042
2023-06-21 11:00:00 -0.060
2023-06-21 17:00:00  0.031
2023-06-21 19:00:00 -0.083

[2096 rows x 1 columns]

In [341]:
pearson_corr = np.corrcoef(EU_GU['EU'].tail(2090), UJ_returns['UJ'].tail(2090))
pearson_corr

array([[ 1.        , -0.00681756],
       [-0.00681756,  1.        ]])

In [342]:
pearson_corr = np.corrcoef(UJ_returns['UJ'].tail(2090), EU_GU['GU'].tail(2090))
pearson_corr

array([[ 1.00000000e+00, -4.01296288e-05],
       [-4.01296288e-05,  1.00000000e+00]])

In [343]:
pearson_corr = np.corrcoef(EU_GU['Spread'].tail(2090), UJ_returns['UJ'].tail(2090))
pearson_corr

array([[ 1.        , -0.00965591],
       [-0.00965591,  1.        ]])

In [344]:
def corr_measure(pearson_corr, i):
    if pearson_corr > abs(0.5):
        print(f'Lag {i} shows a moderate correlation')
    else:
        print(f'No Correlation at {i}')

for i in range(1, 24):
    # Make a copy of the original dataframe
    UJ_returns_copy = UJ_returns.copy()

    # Shift the index in the copy back by one hour
    UJ_returns_copy.index = UJ_returns_copy.index - pd.Timedelta(hours=i)

    # Keep only the rows in UJ_returns_copy that match the index in EU_GU
    UJ_returns_copy = UJ_returns_copy[UJ_returns_copy.index.isin(EU_GU.index)]
    
    min_length = min(len(EU_GU), len(UJ_returns_copy))

    pearson_corr = np.corrcoef(EU_GU['EU'].tail(min_length), UJ_returns_copy['UJ'].tail(min_length))[0, 1]
    corr_measure(pearson_corr, i)
    
    pearson_corr = np.corrcoef(UJ_returns_copy['UJ'].tail(min_length), EU_GU['GU'].tail(min_length))[0, 1]
    corr_measure(pearson_corr, i)
    
    pearson_corr = np.corrcoef(EU_GU['EU'].tail(min_length), UJ_returns_copy['UJ'].tail(min_length))[0, 1]
    corr_measure(pearson_corr, i)

No Correlation at 1
No Correlation at 1
No Correlation at 1
No Correlation at 2
No Correlation at 2
No Correlation at 2
No Correlation at 3
No Correlation at 3
No Correlation at 3
No Correlation at 4
No Correlation at 4
No Correlation at 4
No Correlation at 5
No Correlation at 5
No Correlation at 5
No Correlation at 6
No Correlation at 6
No Correlation at 6
No Correlation at 7
No Correlation at 7
No Correlation at 7
No Correlation at 8
No Correlation at 8
No Correlation at 8
No Correlation at 9
No Correlation at 9
No Correlation at 9
No Correlation at 10
No Correlation at 10
No Correlation at 10
No Correlation at 11
No Correlation at 11
No Correlation at 11
No Correlation at 12
No Correlation at 12
No Correlation at 12
No Correlation at 13
No Correlation at 13
No Correlation at 13
No Correlation at 14
No Correlation at 14
No Correlation at 14
No Correlation at 15
No Correlation at 15
No Correlation at 15
No Correlation at 16
No Correlation at 16
No Correlation at 16
No Correlation at 1

## Hypothesis 
Currency prices whose sessions open prior to other sessions can be a leading indicator of prices for currencies sessions not yet opened, which can be found through interdependent and time lagged analysis. For example, if AUDUSD returns positive in the first hour of the Syd open, USDJPY is expected to return positive too. 

## Method

Gather data on the first 5min to 60min bars of each open, starting with Sydney. Will base currencies against the USD Markets open in the following order:
GMT Time (MT5 is GMT +3)
- Sydney: 9PM / 21:00 (AUDUSD)
- Tokyo: 12AM / 00:00 (USDJPY)
- London: 7AM / 7:00(GBPUSD)
- New York: 1PM / 13:00 (EURUSD)

Run a Pearson Correlation and a Granger Causality method on the gathered data and the respective currencies.



In [144]:
def corr_tool(symbol1, symbol2, timeframe, bars):
    print(f'Starting Pearson Correlation Analysis for {symbol1}, {symbol2} at {timeframe} for {bars} bars.')

    pair1 = get_rates(symbol1, timeframe, bars)
    pair2 = get_rates(symbol2,  timeframe, bars)
    
    s1 = input('Start Time for X?')
    s2 = input('End time for X?')

    e1 = input('Start time for Y?')
    e2 = input('End time for Y?')

    print('Times to investigate are:'
          f'\n{s1} to {s2} and {e1} to {e2}')
    
    pair1_returns = pair1['open'] - pair1['close']
    pair2_returns = pair2['open'] - pair2['close']

    lst = []

    un_corr = []

    for i in range(50):
        pearson_corr = np.corrcoef(syd_opens['Syd Pip Return'].tail(i), tokyo_opens['Tko Pip Return'].tail(i))
        if pearson_corr[0][1] > 0.5:
            # print(f'Pearson correlation {pearson_corr[0][1]} on lag {i}')
            lst.append(i)
        else:
            un_corr.append(i)
            
    print(f'Lags that have a correlation higher than 0.5 are:'
        f'\n{lst}')
    print(f'Total Lags: {len(lst)}')

    import datetime

    day_counts = {}

    for i in lst:
        date = syd_opens.index[i]
        day_name = date.day_name()

        if day_name not in day_counts:
            day_counts[day_name] = 0

        day_counts[day_name] += 1
    print(f'Days that have correlations between AUDUSD and USDJPY of more than 0.5 are:')

    for day, count in day_counts.items():
        print(f'{day}: {count}')
        
    day_counts = {}

    for i in un_corr:
        date = syd_opens.index[i]
        day_name = date.day_name()

        if day_name not in day_counts:
            day_counts[day_name] = 0

        day_counts[day_name] += 1
    print(f'Days that do not have correlations between AUDUSD and USDJPY of more than 0.5 are:')

    for day, count in day_counts.items():
        print(f'{day}: {count}')

In [45]:
corr_tool('AUDUSD.a', 'AUDJPY.a', mt5.TIMEFRAME_H1, 50000)

Starting Pearson Correlation Analysis for AUDUSD.a, AUDJPY.a at 16385 for 50000 bars.


Start Time for AUDUSD.a? 19:00
End time for AUDUSD.a? 19:59
Start time for AUDJPY.a? 20:00
End time for AUDJPY.a 20:59


Times to investigate are:
19:00 to 19:59 and 20:00 to 20:59
Lags that have a correlation higher than 0.5 are:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
Total Lags: 50
Days that have correlations between AUDUSD.a and AUDJPY.aof more than 0.5 are:
Monday: 10
Tuesday: 10
Wednesday: 10
Thursday: 10
Friday: 10
Days that do not have correlations between AUDUSD.a and AUDJPY.a of more than 0.5 are:


In [174]:
#Starting with AUDUSD, Hourly Timeframe 
AUDUSD = get_rates('AUDUSD.a', mt5.TIMEFRAME_H1, 50000)
syd_opens = AUDUSD.between_time('19:00','19:59')
syd_opens['returns'] = syd_opens['close'] - syd_opens['open']
USDJPY = get_rates('USDJPY.a', mt5.TIMEFRAME_H1, 50000)
tokyo_opens = USDJPY.between_time('20:00', '20:59')
tokyo_opens['returns'] = tokyo_opens['close'] - tokyo_opens['open']
tail = 50 
pearson_corr = np.corrcoef(syd_opens['returns'].tail(tail), tokyo_opens['returns'].tail(tail)) 
pearson_corr

array([[1.        , 0.50440698],
       [0.50440698, 1.        ]])

In [169]:
def initial_mini_corr(s1, s2, bars = 10000):
    
    
    ts1_1 = input(f'Start Time for {s1}?')
    ts1_2 = input(f'End time for {s1}?')

    ts2_1 = input(f'Start time for {s2}?')
    ts2_2 = input(f'End time for {s2}?')
    
    p1 = get_rates(s1, mt5.TIMEFRAME_H1, 50000)
    p1 = p1.between_time(ts1_1, ts1_2)
    p1['returns'] = p1['close'] - p1['open']
    p2 = get_rates(s2, mt5.TIMEFRAME_H1, 50000)
    p2 = p2.between_time(ts2_1, ts2_2)
    p2['returns'] = p2['close'] - p2['open']
    
    pearson_corr = np.corrcoef(p1['returns'].tail(tail), p2['returns'].tail(tail)) 
    return pearson_corr

In [170]:
initial_mini_corr('AUDUSD.a', 'USDJPY.a')

Start Time for AUDUSD.a? 10:00
End time for AUDUSD.a? 10:59
Start time for USDJPY.a? 13:00
End time for USDJPY.a? 13:59


array([[1.        , 0.07723649],
       [0.07723649, 1.        ]])

In [ ]:
from datetime import datetime, timedelta

def hour_mini_corr(s1, s2, bars = 100):

    correlations = {}  # Store correlations here, keyed by time string

    for h in range(24):  # For each hour of the day
        ts1_1 = datetime.strptime(f'{h}:00', '%H:%M').time()
        ts1_2 = (datetime.combine(datetime.today(), ts1_1) + timedelta(hours=1)).time()

        ts2_1 = (datetime.combine(datetime.today(), ts1_1) + timedelta(hours=1)).time()
        ts2_2 = (datetime.combine(datetime.today(), ts2_1) + timedelta(hours=1)).time()

        # Convert to strings for use in function
        ts1_1, ts1_2, ts2_1, ts2_2 = [t.strftime('%H:%M') for t in [ts1_1, ts1_2, ts2_1, ts2_2]]

        p1 = get_rates(s1, mt5.TIMEFRAME_H1, 50000)
        p1 = p1.between_time(ts1_1, ts1_2)
        p1['returns'] = p1['close'] - p1['open']
        p2 = get_rates(s2, mt5.TIMEFRAME_H1, 50000)
        p2 = p2.between_time(ts2_1, ts2_2)
        p2['returns'] = p2['close'] - p2['open']

        pearson_corr = np.corrcoef(p1['returns'].tail(bars), p2['returns'].tail(bars)) 
        correlations[f'{ts1_1}-{ts2_1}'] = pearson_corr[0, 1]  # Store correlation

    return correlations

In [162]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

def mini_corr(s1, s2, bars = 500):

    results = []

    for offset in range(24):
        for h in range(24):
            
            # start and end times for first time series
            ts1_1 = timedelta(hours=h).seconds // 3600
            ts1_2 = (ts1_1 + 1) % 24
            
            # offset hours for second time series
            ts2_1 = (ts1_1 + 1 + offset) % 24
            ts2_2 = (ts2_1 + 1) % 24
            
            p1 = get_rates(s1, mt5.TIMEFRAME_H1, 50000)
            p1 = p1.between_time(f'{ts1_1:02d}:00', f'{ts1_2:02d}:00')
            p1['returns'] = p1['close'] - p1['open']

            p2 = get_rates(s2, mt5.TIMEFRAME_H1, 50000)
            p2 = p2.between_time(f'{ts2_1:02d}:00', f'{ts2_2:02d}:00')
            p2['returns'] = p2['close'] - p2['open']

            if len(p1['returns']) > 0 and len(p2['returns']) > 0:
                pearson_corr = np.corrcoef(p1['returns'].tail(bars), p2['returns'].tail(bars))[0, 1]

                if abs(pearson_corr) > 0.5:
                    results.append((ts1_1, ts1_2, ts2_1, ts2_2, pearson_corr))
                    
    return results

In [163]:
mini_corr('AUDUSD.a', 'USDJPY.a')

[(13, 14, 13, 14, -0.5069723012444712),
 (14, 15, 14, 15, -0.7897661689149376),
 (15, 16, 15, 16, -0.7678376747086922),
 (16, 17, 16, 17, -0.582745257763089),
 (17, 18, 17, 18, -0.5154347958641352),
 (19, 20, 19, 20, -0.556167066543711),
 (20, 21, 20, 21, -0.612978471752775),
 (21, 22, 21, 22, -0.5632127428717656)]

In [167]:
def v3_mini_corr(s1, s2, bars=100):
    for offset in range(24):
        for hour in range(24):
            ts1_1 = hour
            ts1_2 = (ts1_1 + 1) % 24
            
            ts2_1 = (hour + 1 + offset) % 24
            ts2_2 = (ts2_1 + 1) % 24
            
            # Convert to string format for the 'between_time' function
            ts1_1, ts1_2, ts2_1, ts2_2 = [f'{t:02d}:00' for t in [ts1_1, ts1_2, ts2_1, ts2_2]]
            
            p1 = get_rates(s1, mt5.TIMEFRAME_H1, 50000)
            p1 = p1.between_time(ts1_1, ts1_2)
            p1['returns'] = p1['close'] - p1['open']
            
            p2 = get_rates(s2, mt5.TIMEFRAME_H1, 50000)
            p2 = p2.between_time(ts2_1, ts2_2)
            p2['returns'] = p2['close'] - p2['open']
            
            if len(p1['returns']) < bars or len(p2['returns']) < bars:
                print(f'Insufficient data for {s1} between {ts1_1} and {ts1_2} or {s2} between {ts2_1} and {ts2_2}')
                continue
            
            pearson_corr = np.corrcoef(p1['returns'].tail(bars), p2['returns'].tail(bars))[0, 1]
            
            if abs(pearson_corr) > 0.5:
                print(f'Found correlation {pearson_corr} for {s1} between {ts1_1} and {ts1_2} and {s2} between {ts2_1} and {ts2_2}')


In [168]:
v3_mini_corr('AUDUSD.a', 'USDJPY.a')

Found correlation -0.7307982835086003 for AUDUSD.a between 14:00 and 15:00 and USDJPY.a between 14:00 and 15:00
Found correlation -0.7374479429221158 for AUDUSD.a between 15:00 and 16:00 and USDJPY.a between 15:00 and 16:00
Found correlation -0.5174647667371404 for AUDUSD.a between 16:00 and 17:00 and USDJPY.a between 16:00 and 17:00


In [37]:
#Correlation for AUDJPY Syd Open - USDJPY Tokyo Open
lst = []

un_corr = []

for i in range(50):
    pearson_corr = np.corrcoef(syd_opens['Syd Pip Return'].tail(i), tokyo_opens['Tko Pip Return'].tail(i))
    if pearson_corr[0][1] > 0.5:
        # print(f'Pearson correlation {pearson_corr[0][1]} on lag {i}')
        lst.append(i)
    else:
        un_corr.append(i)
        
print(f'Lags that have a correlation higher than 0.5 are:'
      f'\n{lst}')
print(f'Total Lags: {len(lst)}')

Lags that have a correlation higher than 0.5 are:
[6, 7, 9, 10, 14, 15, 16, 17, 18, 19, 20, 21, 22, 25, 33, 34, 35, 36, 39, 49]
Total Lags: 20


In [38]:
import datetime

day_counts = {}

for i in lst:
    date = syd_opens.index[i]
    day_name = date.day_name()

    if day_name not in day_counts:
        day_counts[day_name] = 0

    day_counts[day_name] += 1
print(f'Days that have correlations between AUDUSD and USDJPY of more than 0.5 are:')

for day, count in day_counts.items():
    print(f'{day}: {count}')

Days that have correlations between AUDUSD and USDJPY of more than 0.5 are:
Tuesday: 4
Wednesday: 3
Friday: 6
Monday: 5
Thursday: 2


In [39]:
import datetime

day_counts = {}

for i in un_corr:
    date = syd_opens.index[i]
    day_name = date.day_name()

    if day_name not in day_counts:
        day_counts[day_name] = 0

    day_counts[day_name] += 1
print(f'Days that do not have correlations between AUDUSD and USDJPY of more than 0.5 are:')

for day, count in day_counts.items():
    print(f'{day}: {count}')

Days that do not have correlations between AUDUSD and USDJPY of more than 0.5 are:
Monday: 5
Tuesday: 6
Wednesday: 7
Thursday: 8
Friday: 4


In [42]:
def corr_tool(symbol1, symbol2, timeframe, bars):
    print(f'Starting Pearson Correlation Analysis for {symbol1}, {symbol2} at {timeframe} for {bars} bars.')

    s1 = input(f'Start Time for {symbol1}?')
    s2 = input(f'End time for {symbol1}?')

    e1 = input(f'Start time for {symbol2}?')
    e2 = input(f'End time for {symbol2}')

    pair1 = get_rates(symbol1, timeframe, bars)
    explored_seg1 = pair1.between_time(s1, s2)
    pair2 = get_rates(symbol2,  timeframe, bars)
    explored_seg2 = pair2.between_time(e1, e2)
    
    print('Times to investigate are:'
          f'\n{s1} to {s2} and {e1} to {e2}')
    
    pair1_returns = pair1['open'] - pair1['close']
    pair2_returns = pair2['open'] - pair2['close']

    lst = []

    un_corr = []

    for i in range(50):
        pearson_corr = np.corrcoef(pair1_returns.tail(50), pair2_returns.tail(50))
        if pearson_corr[0][1] > 0.5:
            # print(f'Pearson correlation {pearson_corr[0][1]} on lag {i}')
            lst.append(i)
        else:
            un_corr.append(i)
            
    print(f'Lags that have a correlation higher than 0.5 are:'
        f'\n{lst}')
    print(f'Total Lags: {len(lst)}')

    import datetime

    day_counts = {}

    for i in lst:
        date = syd_opens.index[i]
        day_name = date.day_name()

        if day_name not in day_counts:
            day_counts[day_name] = 0

        day_counts[day_name] += 1
    print(f'Days that have correlations between {symbol1} and {symbol2}of more than 0.5 are:')

    for day, count in day_counts.items():
        print(f'{day}: {count}')
        
    day_counts = {}

    for i in un_corr:
        date = syd_opens.index[i]
        day_name = date.day_name()

        if day_name not in day_counts:
            day_counts[day_name] = 0

        day_counts[day_name] += 1
    print(f'Days that do not have correlations between {symbol1} and {symbol2} of more than 0.5 are:')

    for day, count in day_counts.items():
        print(f'{day}: {count}')

In [43]:
corr_tool('EURUSD.a', 'GBPUSD.a', mt5.TIMEFRAME_H1, 50000)

Starting Pearson Correlation Analysis for EURUSD.a, GBPUSD.a at 16385 for 50000 bars.


Start Time for EURUSD.a? 10:00
End time for EURUSD.a? 10:59
Start time for GBPUSD.a? 16:00
End time for GBPUSD.a 16:59


Times to investigate are:
10:00 to 10:59 and 16:00 to 16:59
Lags that have a correlation higher than 0.5 are:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
Total Lags: 50
Days that have correlations between EURUSD.a and GBPUSD.aof more than 0.5 are:
Monday: 10
Tuesday: 10
Wednesday: 10
Thursday: 10
Friday: 10
Days that do not have correlations between EURUSD.a and GBPUSD.a of more than 0.5 are:


In [41]:
pair1 = get_rates('EURUSD.a', mt5.TIMEFRAME_H1, 10000)
pair2 = get_rates('GBPUSD.a',  mt5.TIMEFRAME_H1, 10000)